; PlatformIO Project Configuration File
[env:seeed_xiao_esp32c3]
platform = espressif32 @ 6.4.0
board = seeed_xiao_esp32c3
framework = arduino
board_build.partitions = opp_partitions.csv
board_build.filesystem = littlefs
lib_deps = 
	makuna/NeoPixelBus@^2.8.4
build_flags = 
	-Os

[env:esp32c3_32px_strip]
platform = espressif32 @ 6.4.0
board = seeed_xiao_esp32c3
framework = arduino
board_build.partitions = opp_partitions.csv
board_build.filesystem = littlefs
lib_deps = 
	makuna/NeoPixelBus@^2.8.4
build_flags = 
	-Os
	-D STRIP_32PX
