; PlatformIO Project Configuration File for Master Nunchuk Bridge
[env:seeed_xiao_esp32c3]
platform = espressif32 @ 6.4.0
board = seeed_xiao_esp32c3
framework = arduino
board_build.partitions = huge_app.csv
build_flags = 
	-Os
